language: c
compiler: gcc
install: sudo apt-get install texlive texlive-bibtex-extra texlive-xetex
script: cd book && ./build && cd ..
deploy:
  provider: releases
  api_key:
    secure: GD0c+hmACjBZHAXDAwBokIx0+VVEmNxFoX9cM1wG8TIA8DDpMn9Zjz02/8pZWylRQfwwrH7bY3L5XLdZ5lUTOvO7iKY3AKXT5OFFMhrKo8/U9KdFDOj7P1SEe3Bq5hZvVv2XR9ntmVudOfJGL798FTcdoNWUVmJx3R35Vbd+U/Y=
  file: book/lysa.pdf
  on:
    repo: learnmath/lysa
    branch: develop
