language: c
compiler: gcc
install: sudo apt-get install biblatex texlive texlive-latex-extra texlive-bibtex-extra
  texlive-xetex texlive-math-extra texlive-latex3
script: cd book && ./build && cd ..
after_success: scripts/deploy.sh
notifications:
  irc: 
    channels:
      - "chat.freenode.net#learnmath"
