language: c
compiler: gcc
install: sudo apt-get install biblatex texlive texlive-latex-extra texlive-bibtex-extra
  texlive-xetex texlive-math-extra texlive-latex3
script: cd book && ./build && cd ..
deploy:
  provider: releases
  api_key:
    secure: GD0c+hmACjBZHAXDAwBokIx0+VVEmNxFoX9cM1wG8TIA8DDpMn9Zjz02/8pZWylRQfwwrH7bY3L5XLdZ5lUTOvO7iKY3AKXT5OFFMhrKo8/U9KdFDOj7P1SEe3Bq5hZvVv2XR9ntmVudOfJGL798FTcdoNWUVmJx3R35Vbd+U/Y=
  file: book/lysa.pdf
  skip_cleanup: true
  on:
    tags: true
    repo: learnmath/lysa
    all_branches: true
after_success:
- export USER="lysa"
- export HOST="184.164.72.39"
- openssl aes-256-cbc -K $encrypted_6d2a7d4982c7_key -iv $encrypted_6d2a7d4982c7_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- chmod 600 deploy_rsa
- ssh -o "StrictHostKeyChecking no" $USER@$HOST
- scp -i deploy_rsa book/lysa.pdf $USER@$HOST:html/lysa-build$TRAVIS_JOB_ID.pdf
